#!/bin/bash
#written by wenhao

[ $(id -u) -ne 0 ] && { echo $'\e[31mPlease run this script by root.\e[0m';exit 1; }

[ -f config ] && . config || { echo "config file not found.";exit 1; }

# source all config
for checkdir in $CheckDirs
do
    [ -f $checkdir/config ] && . $checkdir/config
done

# run chech scripts
for checkscript in $CheckScripts
do
{
    if [ -f $checkscript ];then
        bash $checkscript
    fi
} &
done

wait
